name: Max Vehicle Window
language: python
variables:
  - name: input
    inputType: InputTopic
    description: ''
    defaultValue: image-vehicles
    required: false
  - name: output
    inputType: OutputTopic
    description: ''
    defaultValue: max-vehicles
    required: false
  - name: output2
    inputType: OutputTopic
    description: ''
    defaultValue: max-vehicles-agg
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
